### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by Mingxiao-Li** [ggeorgak11/CM2#1]
I always got "ERROR: Could not find a version that satisfies the requirement <packagename> (from versions: none)
ERROR: No matching distribution found for <packagename>"  for quite a lot of packages in the requirements.txt when I run pip install -r requirements.My pip is the newest version. Could you kindly inform me how did you install all the necessary package ?

**Comment by ggeorgak11** [comment]
Sorry the requirements.txt was outdated. I pushed a new version.

**Comment by Mingxiao-Li** [comment]
> 

Thanks, but I still got quite a lot of errors. Could you install all the necessary packages by just using "pip install -r requirement.txt" ?

**Comment by ggeorgak11** [comment]
Yes I had no issue. What are the errors exactly? What system are you using?

**Comment by Mingxiao-Li** [comment]
Sorry, I got another problem. Could you kindly inform me how did you install habitat-sim with CUDA version ?  Did you install it from source or conda ? Thanks

**Comment by ggeorgak11** [comment]
I built from source following the instructions here:
https://github.com/facebookresearch/habitat-sim/blob/main/BUILD_FROM_SOURCE.md
Make sure to clone the v0.1.7 branch and include the --with-cuda flag to build.
Also look at the Common build issues. I had to use --parallel 1 otherwise my installation would hang.

**Comment by Mingxiao-Li** [comment]
> I built from source following the instructions here:
> https://github.com/facebookresearch/habitat-sim/blob/main/BUILD_FROM_SOURCE.md
> Make sure to clone the v0.1.7 branch and include the --with-cuda flag to build.
> Also look at the Common build issues. I had to use --parallel 1 otherwise my installation would hang.

Many thanks for the explanation. I tried to follow  the instruction in the BUILD_FROM_SOURCE.md, but I always got the "Cake will not be able to correctly generate this project" error, have you ever came across this issue ?

**Comment by ggeorgak11** [comment]
I have not seen this before sorry
