### ISSUE TITLE
Train and eval problem

### ISSUE THREAD

**Issue by Hoyyyaard** [ggeorgak11/CM2#2]
Hello ，my training time of CM with all scene takes over 600 hours and eval with one scene takes two days ; Is these phenomena normal？
I use 7 GPUS with TITAN Xp

train command:  python main.py --name train_cm2_allscene --stored_episodes_dir /mnt/cephfs/dataset/VLN-CE/data/cm2episodes/ --log_dir logs/ --is_train --summary_steps 500 --image_summary_steps 1000 --test_steps 20000 --checkpoint_steps 50000 --pad_text_feat --batch_size 40 --finetune_bert_last_layer --use_first_waypoint --vln_no_map --sample_1

eval command: python main.py --name run_test_cm2_val-unseen --root_path /mnt/cephfs/home/jidongyu/zhihongyan/CM2-master/habitat-lab/ --scenes_dir data/scene_datasets/ --model_exp_dir /mnt/cephfs/home/jidongyu/zhihongyan/CM2-master/logs/train_cm2/checkpoints/best --log_dir logs/ --img_segm_model_dir /mnt/cephfs/home/jidongyu/zhihongyan/CM2-master/segm_model/ --scenes_list 2azQ1b91cZZ --gpu_capacity 1 --split val_seen --use_first_waypoint --goal_conf_thresh 0.2 --vln_no_map

**Comment by ggeorgak11** [comment]
You have already generated the training data and you are running the training offline, right? If that is the case then 600 hours is way too much. We trained on 2 GTX A6000 gpus using 700K examples for 2-3 days. Maybe you need to set up DistributedDataParallel if you are running on that many gpus? 

The eval on one scene should not take more than half a day in the worst case. Note that in eval command you posted you need to specify --split val_unseen for scene 2azQ1b91cZZ

**Comment by Mingxiao-Li** [comment]
I am wondering how many epoch did you train for the best model?

**Comment by Mingxiao-Li** [comment]
> You have already generated the training data and you are running the training offline, right? If that is the case then 600 hours is way too much. We trained on 2 GTX A6000 gpus using 700K examples for 2-3 days. Maybe you need to set up DistributedDataParallel if you are running on that many gpus?
> 
> The eval on one scene should not take more than half a day in the worst case. Note that in eval command you posted you need to specify --split val_unseen for scene 2azQ1b91cZZ

I have trained the model for 100 epoch, and the evaluation results seem not that perfect. May I ask how many epoch did you train the best model ?

**Comment by ggeorgak11** [comment]
Closing this issue as it is addressed [here](https://github.com/ggeorgak11/CM2/issues/4).
