### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by Mingxiao-Li** [ggeorgak11/CM2#3]
Hi, I found that in the dataloader, you also filter the dataset by checking whether dial is at the same height as start position. I am quite confused about this. Why this filtering is necessary ? And does it mean that the model doesn't train and test on the whole VLNCE dataset ?

**Comment by ggeorgak11** [comment]
I was trying to check how many episodes span multiple floors and I forgot about it. The model was trained and tested on the whole VLNCE dataset as reported in the paper. I pushed an update that removed this check.
